ARG sourceimage=xplitradeorg/xplitrade
ARG sourcetag=develop_freqai
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-freqai.txt requirements-freqai-rl.txt /xplitrade/

RUN pip install -r requirements-freqai-rl.txt --user --no-cache-dir
